services:
  - type: web
    name: object-detection-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.9"
    autoscale: true
    healthCheckPath: /  # Optional, path to check if your app is running
