services:
  - type: web
    name: object-detection-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: "3.10"  # Change to 3.9 if 3.10 still causes issues
    autoscale: true
    healthCheckPath: /
